#ifndef CONFIG_H
#define CONFIG_H

#define SERIAL_BAUD_RATE 115200

#define FIRMWARE_VERSION_MAJOR 1
#define FIRMWARE_VERSION_MINOR 0
#define FIRMWARE_VERSION_PATCH 0
#define FIRMWARE_VERSION_STR   "1.0.0"

#endif // CONFIG_H